# Generated by Django 3.0.2 on 2020-01-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('opis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dostepny', models.BooleanField()),
            ],
        ),
    ]
